const plalist = {
  title: "Hip-Hop Hits",
  songs: [
    {
      id: 1,
      artist: "Public Enemy",
      songName: "Fight the Power",
      year:  1989,
      isHot: false,
      fileUrl: "https://www.example.com/public-enemy-fight-the-power",
      cover: "https://www.example.com/public-enemy-fight-the-power-cover.jpg",
      info: {
        duration: "4:42",
        totalTracksCount: 12,
      },
    },
    {
      id: 2,
      artist: "Vanilla Ice",
      songName: "Ice Ice Baby",
      year:  1990,
      isHot: false,
      fileUrl: "https://www.example.com/vanilla-ice-ice-ice-baby",
      cover: "https://www.example.com/vanilla-ice-ice-ice-baby-cover.jpg",
      info: {
        duration: "4:29",
        totalTracksCount: 10,
      },
    },
    {
      id: 3,
      artist: "MC Hammer",
      songName: "You Can't Touch This",
      year:  1990,
      isHot: false,
      fileUrl: "https://www.example.com/mc-hammer-you-cant-touch-this",
      cover: "https://www.example.com/mc-hammer-you-cant-touch-this-cover.jpg",
      info: {
        duration: "4:16",
        totalTracksCount: 14,
      },
    },
    {
      id: 4,
      artist: "Brand Nubian",
      songName: "Brand Nubian",
      year:  1990,
      isHot: false,
      fileUrl: "https://www.example.com/brand-nubian-brand-nubian",
      cover: "https://www.example.com/brand-nubian-brand-nubian-cover.jpg",
      info: {
        duration: "4:35",
        totalTracksCount: 11,
      },
    },
    {
      id: 5,
      artist: "50 Cent",
      songName: "In da Club",
      year:  2003,
      isHot: false,
      fileUrl: "https://www.example.com/50-cent-in-da-club",
      cover: "https://www.example.com/50-cent-in-da-club-cover.jpg",
      info: {
        duration: "3:13",
        totalTracksCount: 16,
      },
    },
    {
      id: 6,
      artist: "DMX",
      songName: "X Gon' Give It To Ya",
      year:  2003,
      isHot: false,
      fileUrl: "https://www.example.com/dmx-x-gon-give-it-to-ya",
      cover: "https://www.example.com/dmx-x-gon-give-it-to-ya-cover.jpg",
      info: {
        duration: "3:38",
        totalTracksCount: 15,
      },
    },
    {
      id: 7,
      artist: "Eminem feat 50 Cent, Cashis, Lloyd Banks",
      songName: "You Don't Know",
      year:  2006,
      isHot: false,
      fileUrl: "https://www.example.com/eminem-feat-50-cent-cashis-lloyd-banks-you-dont-know",
      cover:
        "https://www.example.com/eminem-feat-50-cent-cashis-lloyd-banks-you-dont-know-cover.jpg",
      info: {
        duration: "4:17",
        totalTracksCount: 18,
      },
    },
    {
      id: 8,
      artist: "Eminem",
      songName: "Rap God",
      year:  2013,
      isHot: true,
      fileUrl: "https://www.example.com/eminem-rap-god",
      cover: "https://www.example.com/eminem-rap-god-cover.jpg",
      info: {
        duration: "6:03",
        totalTracksCount: 20,
      },
    },
  ],
};
